// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ConvertRequest struct {
	LongUrl string `json:"long_url"`
}

type ConvertResponse struct {
	ShortUrl string `json:"short_url"`
}

type ShowRequest struct {
	ShortUrl string `path:"short_url"`
}

type ShowResponse struct {
	LongUrl string `json:"long_url"`
}
