// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: shortener.api

package types

type ConvertRequest struct {
	LongUrl string `json:"long_url" validate:"required,url"`
}

type ConvertResponse struct {
	ShortUrl string `json:"short_url"`
}

type ShowRequest struct {
	ShortUrl string `path:"short_url"`
}

type ShowResponse struct {
	LongUrl     string `json:"long_url"`
	RiskWarning string `json:"risk_warning,omitempty"` // 安全警告信息
}

type PreviewRequest struct {
	ShortUrl string `path:"short_url"`
}

type PreviewResponse struct {
	ShortUrl    string   `json:"short_url"`
	LongUrl     string   `json:"long_url"`
	Summary     string   `json:"summary"`
	Keywords    []string `json:"keywords"`
	RiskLevel   string   `json:"risk_level"`
	RiskReason  string   `json:"risk_reason"`
}
